apiVersion: v1
kind: Service
metadata:
  name: ${WEB_APP}
  namespace: ${NAMESPACE}
  labels:
    app: ${WEB_APP}
spec:
  type: ClusterIP
  selector:
    app: ${WEB_APP}
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
